### ISSUE TITLE
Enable stack tracing output when an error happens

### ISSUE THREAD

**Issue by marcoarthur** [subutai-io/cdn#200]
This is a highly wanted feature, since we can make postmortem debug much better. And will lead us to deal with possible difficult concurrent problems happening.

**Comment by crioto** [comment]
@marcoarthur AFAIK go apps always produce backtrace on crashes. So can you elaborate on this issue please?

**Comment by marcoarthur** [comment]
@crioto I was thinking in improve of log and have a debug flag to be set, like using asserts in C. So we can run program with debug symbols. That was the idea at time. But yeah not really well elaborated.

**Comment by crioto** [comment]
ok @marcoarthur thanks for your answer. Currently we are working on refactor of the code, so probably this issue is not needed, since we will implement proper logging and output of debug messages. Also we are making code much more "testable". So I would like to mark this issue as `invalid` and close it. WDYT?

**Comment by marcoarthur** [comment]
Yes, I agree closing it and mark it invalid.
