### ISSUE TITLE
PGP signing of APT repositories

### ISSUE THREAD

**Issue by happyaron** [subutai-io/cdn#240]
The apt repository needs to be signed by PGP key pair whose public part preloaded in the target system, so that apt on target system can authenticate the packages, resisting from MITM attacks.

Ordinary secured APT repository consists of several components:

- **Release** files: required, PGP signed, contains checksums of *Packages* and other indices.
- **Packages** indices: required, index of binary packages, contains checksums of packages
- **Sources** indices: optional, index of source packages, contains checksums of sources
- **Contents** indices: optional, index of package contents
- **Translation** indices: optional, localization of package descriptions

Every time the repository maintenance software publishes a new set of packages (called a _dinstall_  run in dak), the *Packages* indices are refreshed and *Release* files are regenerated and detached signed (inline clear sign is supported, but for compatibility it's better to provide a Release.gpg that's detached signature alongside the unsigned Release file).

All of the above meta files can be served as XZ compressed to speed up the process (with .xz suffix), and apt will fallback to .gz or .bz2 and finally plain text if they are not found (HTTP 404).

For the checksums, SHA256 is recommended, and MD5Sum and SHA1 should present for compatibility reasons.

**Comment by marcoarthur** [comment]
I think if we set up the same security protocol for an apt repository running dak suite we end up reproducing something about 50k of python LOC . This is of course not feasible, since, we could think of a solution in terms of:
1) Remove .deb uploaded from gorjun.
2) keep it and think of a solution with dak, so we end up with a proper Debian repository, so any uploads of a deb file will be routed to this.

@akarasulu , @Dilshat  do you see others alternatives?

**Comment by marcoarthur** [comment]
The other alternative is to follow a minimal approach: create the Release and Package files and use a signed PGP certificate. We are making a patch for this. And see if apt could them use this repository. So the action plan:
1) Patch gorjun to generate Required files: Package and Release 2) Provide PGP security on these files

**Comment by Dilshat** [comment]
Like it

**Comment by marcoarthur** [comment]
Updates: https://github.com/subutai-io/gorjun/compare/apt-repo we can make part 1 of the plan.

 But we need open (@Dilshat @akarasulu  ) discussion to part 2. Since PGP carries sensitive information (passphase) that should be stored safely. Currently, options considered

1.  Set our config file with 600 permissions code save plain text password (easy to implement)
2.  Sign without passphrase (also easy to implement) 
3.  Store passphase in a encrypted manner, such as shadow passwd ( middle to implement)

Other options are welcome

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by emli** [comment]
1) Add our cdn to /etc/apt/sources.list this  `deb http://cdn.subut.ai:8080/kurjun/rest/apt /` 
2) Run `sudo apt-get update`

**Comment by amol4anoff** [comment]
Done in prod.
